### ISSUE TITLE
Open URLs with App (Uni Links)

### ISSUE THREAD

**Issue by luke-** [luke-/app#13]
It would be great it links to the active HumHub URL (e.g. via E-Mail) will be opened inside the app and not inside the standard browser.

```
> I don’t think it’s possible, that the App dynamically registers URL Prefixes.

I did some tests with Rocket.chat mobile app which allows you to write the domain of the Rocket instance.
I received a notification by email, and when I click on the link in the email for the first time it asks me if I want to open it in the Rocket app or in the Browser. Choosing the app opens the page correctly in the app.
So it should work for Humhub to!
```

https://community.humhub.com/comment/perma?id=43822

**Comment by PrimozRatej** [comment]
https://pub.dev/packages/uni_links

**Comment by PrimozRatej** [comment]
This can be accomplished with the following data definition for and redirect intent (for now impl. only for android but it's also possible for iOS): 
`<data android:scheme="https" android:host="*.humhub.com" />`
We are intercepting all redirects that follow the format: https://{something}.humhub.com/{anything}

PROBLEM: 
- If the user is logged in to `https://ws_mike.humhub.com` and receives an intent for `https://ws_bob.humhub.com`, we need to consider the following:
  - Should we redirect the user to the new instance, and if so, how?
  - Do we overwrite the existing manifest or allow for a multi-instance app?
  - This would allow the user to be logged in to two different workspaces at the same time.

@luke- , how would you suggest we proceed in this case?

**Comment by luke-** [comment]
@PrimozRatej Usually HumHub installations run under their own domain, e.g. https://social.example.com - can we somehow cover these cases as well?

Can we simply open mistakenly intercepted Intends with the default browser?


It is probably not possible to change the "manifest" of the app during runtime or?

**Comment by PrimozRatej** [comment]
@luke-  Getting the intent for fully dynamic links is not possible. The definition for URL intents is defined in build time so we need to know/have some kind of URL  naming scheme for those URLs beforehand.

We can open mistakenly intercepted Intents in the browser, but that would mean redirecting the intent to the app, the app will be opened and will redirect the user to the browser.

The "manifest" of the app can be changed during runtime which would mean clearing the config. for the current manifest and save value for the intent if we want to do so.

**Comment by luke-** [comment]
@PrimozRatej Can we use a parameter or extension to identify HumHub requests? 

e.g. we could add a **query param** `humhub=1` to all Notification and Activity Links.  e.g. `https://intranet.example.com/notification/12354?humhub=1&someother=5`

**Comment by PrimozRatej** [comment]
Yes, that will work but it needs to be really something identical something that only we would use.

**Comment by PrimozRatej** [comment]
@luke- 
Update: This will not work for query params, the problem is that part after the "?" mark is not matched against anything (filter ignores it).
Source: https://stackoverflow.com/questions/7277480/match-http-parameters-in-url-with-android-intent-filters

**Comment by luke-** [comment]
@PrimozRatej Thanks for the info. I would postpone this feature to a later app version.
