### ISSUE TITLE
Session, App Token & Header 

### ISSUE THREAD

**Issue by PrimozRatej** [luke-/app#15]

**Comment by luke-** [comment]
@PrimozRatej  

Procedure should be:

- When a *new* URL is entered in the opener, create a random token (e.g. 32 chars) and store it.
- Pass this token via the header `x-humhub-app-token` with each request.
- As soon as `hideOpener` or another URL is specified in the opener, the token should be reset.


(If the header is not available, we could possibly transfer the token differently).

**Comment by PrimozRatej** [comment]
https://github.com/luke-/app/pull/39#discussion_r1101901734

**Comment by luke-** [comment]
@PrimozRatej Thank you the token header now appears.

Can you please remove the headers `my-header-value-01` and `my-header-value-02`.

An additional header `x-humhub-app` with the value of the current app version would be cool though!

**Comment by PrimozRatej** [comment]
Shure on it

**Comment by PrimozRatej** [comment]
![image](https://user-images.githubusercontent.com/10835179/218268049-ed1b5c23-b713-4403-a11d-79871cd89cb0.png)

**Comment by luke-** [comment]
@PrimozRatej great, thank you!
