### ISSUE TITLE
GitHub Actions: Android Deployment

### ISSUE THREAD

**Issue by luke-** [luke-/app#2]

**Comment by PrimozRatej** [comment]
For now, implemented only the generation of the .apk file, will move this to milestone v0.2

**Comment by PrimozRatej** [comment]
I have created a GitHub Actions CI/CD pipeline for automatic deployment. However, there are still some configurations that need to be completed, such as creating a .jks signing certificate keystore and enabling the Google service API in the Play console. These tasks can only be done by you, as the owner of the GitHub project and the Play console. To help you with these remaining tasks, I have provided you with the following instructions.

[How to set up APK release signing.pdf](https://github.com/luke-/app/files/10494448/How.to.set.up.APK.release.signing.pdf)


[create_jks_and_encode_it_to_base_64.txt](https://github.com/luke-/app/files/10494450/create_jks_and_encode_it_to_base_64.txt)

**Comment by luke-** [comment]
@PrimozRatej Thank you for the instructions. I've done all steps. Let me know if I should do anything else.

**Comment by PrimozRatej** [comment]
Look like the Keystore base64 is not in the right format. https://github.com/luke-/app/actions/runs/4038331102/jobs/6942254834

**Comment by PrimozRatej** [comment]
Get the Google Play store ready to publish the app instructions and setup.

[Get Google Play store ready to publish the app HumHub.pdf](https://github.com/luke-/app/files/10533505/Get.Google.Play.store.ready.to.publish.the.app.HumHub.pdf)

Data Safety export (this file can be edited locally and then imported to the store if in need of change)

[data_safety_export_hum_hub.csv](https://github.com/luke-/app/files/10533507/data_safety_export_hum_hub.csv)

**Comment by luke-** [comment]
> Get the Google Play store ready to publish the app instructions and setup.
> 
> [Get Google Play store ready to publish the app HumHub.pdf](https://github.com/luke-/app/files/10533505/Get.Google.Play.store.ready.to.publish.the.app.HumHub.pdf)
> 
> Data Safety export (this file can be edited locally and then imported to the store if in need of change)
> 
> [data_safety_export_hum_hub.csv](https://github.com/luke-/app/files/10533507/data_safety_export_hum_hub.csv)

Awesome thanks!

**Comment by luke-** [comment]
> Look like the Keystore base64 is not in the right format. https://github.com/luke-/app/actions/runs/4038331102/jobs/6942254834

@PrimozRatej I've just re-entered the text and restarted the action. Now it seems to run.

**Comment by PrimozRatej** [comment]
Yes now it looks great, The previous attempt failed because the initial upload must be manual to allow the Google Play app to set the bundle ID.

**Comment by luke-** [comment]
@PrimozRatej I am already excited for the first play test version :-)

**Comment by PrimozRatej** [comment]
Feature implemented, the issue can be closed.
