### ISSUE TITLE
Version Tags in Git

### ISSUE THREAD

**Issue by luke-** [luke-/app#20]
Would be great if we can prefix the created version tags with `v` e.g. `v0.1.0` since we use this format in other repos.

**Comment by PrimozRatej** [comment]
This cannot be done for the actual app bundle, but it can be done for the gitversion output.

**Comment by luke-** [comment]
Ok that would be fine. I'm only interested in the Git tags.

**Comment by PrimozRatej** [comment]
This was impl. in the scope of this [commit](https://github.com/luke-/app/commit/f07fa382e35c2dc3f6956bf20ab4e5535727b3ea)
