### ISSUE TITLE
WebView: Base Functionality

### ISSUE THREAD

**Issue by luke-** [luke-/app#4]
The WebView page should mainly display the HumHub installation at previously specified URL.

Other points:
- The `$sessionToken` from #1 should be added to each request via HTTP Header (if not possible as Cookie)
- Other URLs should be opened using the standard browser
- Normal (Browser) navigation behavior inside the WebView for the WebApp (Backward/Forward)

**Comment by PrimozRatej** [comment]
`$sessionToken` for re-login functionality will be implemented in #15
