### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by luke-** [luke-/app#42]
![02_Icon](https://user-images.githubusercontent.com/4736168/220315283-8d0727ef-6aa1-4042-b25e-6f01f2a533cb.png)

**Comment by luke-** [comment]
@PrimozRatej Notifications are still using the flutter default icon on my device. Do we need an additioanl icon here?

**Comment by PrimozRatej** [comment]
Hmm, try to clear the app cache.` Settings>Apps>Apps>HumHub>Storage **ClearData & ClearCache**`
