### ISSUE TITLE
Opener: Check for valid HumHub Installation

### ISSUE THREAD

**Issue by luke-** [luke-/app#6]
The `manifest.json` file should be used to ensure that the URL is a valid HumHub installation with Mobile module.

TODO: Add special HumHub attribute to the `manifest.json`.

**Comment by PrimozRatej** [comment]
The validation of `manifest.json` was already implemented in the scope of #1, @luke- could you elaborate more about the TODO part of the issue?

**Comment by PrimozRatej** [comment]
The feature was implemented, the issue can be closed.
